name: Battlepass
author: JuniorDeveloper
version: ${version}
main: me.JuniorDeveloper.battlepass.BattlepassMain
description: PeyVeyPey
api-version: 1.13


permissions:
  battlepass.Staff:
    description: Permission for staff! Commands acces > balance remove|add

commands:
  bp:
    description: Check your battlepass level!
    usage: /<command> [level|challanges|check|xp|help|balance|withdraw] [level|list] [2|3|4|5]
    aliases: [battlepass, BattlePass]

depend:
  - Vault