name: Battlepass
author: JuniorDeveloper
version: ${version}
main: me.JuniorDeveloper.battlepass.battlepassMain
description: PeyVeyPey


commands:
  bp:
    description: Check your battlepass level!
    usage: /<command> [level|challanges|check|xp] [level|list] [2|3|4|5]
    aliases: [battlepass, BattlePass]