name: Battlepass
author: JuniorDeveloper
version: ${version}
main: me.JuniorDeveloper.battlepass.battlepassMain
description: PeyVeyPey
depend: [Vault]

permissions:
  battlepass.Staff:
    description: Permission for staff! Commands acces > balance remove|add

commands:
  bp:
    description: Check your battlepass level!
    usage: /<command> [level|challanges|check|xp|balance|deposit] [level|list|remove|add|check] [2|3|4|5]
    aliases: [battlepass, BattlePass]